### PR TITLE
feat(volumes): support private go modules

### PR DESCRIPTION
**Pull request by Malinskiy**
Naive attempt at #148

### CODE REVIEW

**Comment by Malinskiy** [comment]
Tests pass locally

If the files are missing on the host then directories with the same names will be created.
This will work Linux + macOS, but not for Windows I believe. No idea how this should look on Windows since I don't use it for any development.

**Comment by charleskorn** [comment]
Thanks for putting this together @Malinskiy. 

Have you tested this on a machine where `~/.gitconfig` doesn't exist? If the local side of a mount doesn't exist, it will be created as a directory, and I'm not sure whether Git allows `~/.gitconfig` to be a directory. (It might be worth adding a test case for this scenario.)

**Comment by Malinskiy** [comment]
Yeah, when the file is missing then docker creates an empty directory and its ignored by git.

I can add a test case, no worries

**Comment by Malinskiy** [comment]
So the sample currently maps the gitconfig when it's not present, I'm not sure how you want to test the private module since I'll have to create a private repo to test it out.
I think the tests should verify this works when the conf is missing. When dealing with private modules user has to change `.gitconfig` and `.ssh` according to his custom requirements anyways (e.g. rewrite github, gitlab, custom git server, ssh key with specific name, etc)

**Comment by charleskorn** [comment]
The more I think about this, the more I'm unsure about whether this belongs in this bundle or not - it may be better for organisations that use private repositories to fork this bundle and configure it in a way appropriate to their situation and developer setup. 

The reason I say this is that a `.gitconfig` file or `.ssh` directory can contain all kinds of configuration options that will not work from within a container (eg. references to files that don't exist in the container, reliance on a SSH agent rather than keys on disk etc.)

---

That aside, one way to test this that doesn't rely on creating a private repo would be to stand up a simple test server that hosts a "private" Git repo and reference that from `go.mod`. What do you think?

**Comment by Malinskiy** [comment]
That's not a problem at all. I've created an internal bundle exactly like you're describing

In general it would be much better to provide only the options that users need, not the whole gitconfig, as well as only the necessary keys, but it's quite a leap from just mounting two volumes.

Up to you if you want to merge this functionality or keep it outside of the main `golang-bundle`, I'm happy with both approaches

**Comment by charleskorn** [comment]
I think it would be best to keep this out for now, at least until we can come up with a better solution that doesn't require mounting both `.gitconfig` and `.ssh` wholesale into the container.

**Pull request closed without merging**
